# Generated by Django 3.2.16 on 2022-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='identificador',
            field=models.CharField(default=1, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
