# Generated by Django 3.2.14 on 2022-09-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('Básica', 'Básica'), ('Avançada', 'Avançada')], default='Básica', max_length=10),
        ),
    ]
