# Generated by Django 3.2.16 on 2022-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0002_professor_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.IntegerField(default=0)),
            ],
        ),
    ]
