# Generated by Django 3.2.8 on 2022-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0003_auto_20220627_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
