# Generated by Django 3.2.16 on 2022-11-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0003_schedulerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulerInfo',
        ),
    ]
