# Generated by Django 3.2.14 on 2022-09-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0003_alter_questao_linguagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plpPool.linguagem'),
        ),
    ]
