# Generated by Django 3.2.8 on 2022-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0004_auto_20220627_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
