# Generated by Django 3.2.16 on 2022-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0005_auto_20221203_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdb',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='backupdb',
            name='file',
            field=models.FileField(upload_to='media/backup/'),
        ),
    ]
