# Generated by Django 3.2.16 on 2022-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0006_auto_20221203_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupdb',
            name='file',
            field=models.FileField(upload_to='backup/'),
        ),
    ]
