# Generated by Django 3.2.8 on 2022-06-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0008_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
