# Generated by Django 3.2.16 on 2023-01-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0008_auto_20221206_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='github',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
