# Generated by Django 3.2.8 on 2022-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='testes_publicos_outpus',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
