# Generated by Django 3.2.16 on 2023-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0009_monitor_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='github',
            field=models.CharField(max_length=250, unique=True, verbose_name='GitHub'),
        ),
    ]
