# Generated by Django 3.2.8 on 2022-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0010_tag_testes_publicos_outpus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='testes_publicos_outpus',
        ),
    ]
