# Generated by Django 3.2.8 on 2022-06-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0012_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plpPool.questao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='sha',
            field=models.CharField(max_length=150, verbose_name='SHA'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='plpPool.tag'),
        ),
    ]
