# Generated by Django 3.2.8 on 2022-06-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0013_auto_20220627_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plpPool.questao'),
        ),
    ]
