# Generated by Django 3.2.8 on 2022-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0014_alter_tag_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='tags',
        ),
        migrations.AddField(
            model_name='questao',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='plpPool.Tag'),
        ),
    ]
