# Generated by Django 3.2.8 on 2022-06-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0016_questao_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('extensao', models.CharField(max_length=50, verbose_name='Extensão')),
            ],
        ),
    ]
