# Generated by Django 3.2.8 on 2022-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0017_linguagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguagem',
            name='compilador',
            field=models.BooleanField(default=False),
        ),
    ]
