# Generated by Django 3.2.8 on 2022-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0018_linguagem_compilador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
