# Generated by Django 3.2.8 on 2022-06-27 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0021_alter_linguagem_extensao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}.[0-9][a-zA-z]?$', 'Formato de período inválido')], verbose_name='Período')),
                ('ativo', models.BooleanField(default=True)),
                ('monitor', models.ManyToManyField(related_name='monitores', to='plpPool.Monitor')),
            ],
        ),
    ]
