# Generated by Django 3.2.8 on 2022-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0022_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='monitor',
        ),
        migrations.AddField(
            model_name='periodo',
            name='monitores',
            field=models.ManyToManyField(to='plpPool.Monitor'),
        ),
    ]
