# Generated by Django 3.2.8 on 2022-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0023_auto_20220627_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
    ]
