# Generated by Django 3.2.8 on 2022-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0025_auto_20220627_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Designates whether this period should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
