# Generated by Django 3.2.8 on 2022-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0026_alter_periodo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica que o período está ativo. Apenas um período pode estar ativo.'),
        ),
    ]
