# Generated by Django 3.2.8 on 2022-06-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0027_alter_periodo_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_basicas', models.IntegerField(default=0, verbose_name='Questões básicas')),
                ('qtd_avancadas', models.IntegerField(default=0, verbose_name='Questões avançadas')),
                ('data', models.DateTimeField()),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('linguagem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plpPool.linguagem')),
                ('periodo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='plpPool.periodo')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
    ]
