# Generated by Django 3.2.8 on 2022-06-28 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0028_auto_20220627_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plpPool.periodo'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='qtd_avancadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Questões avançadas'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='qtd_basicas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Questões básicas'),
        ),
    ]
