# Generated by Django 3.2.8 on 2022-06-29 15:27

import django.core.validators
from django.db import migrations, models
import plpPool.models


class Migration(migrations.Migration):

    dependencies = [
        ('plpPool', '0029_auto_20220627_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nome',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}.[0-9][a-zA-z]?$', 'Formato de período inválido'), plpPool.models.mais_de_um_periodo_ativo], verbose_name='Período'),
        ),
    ]
