# Generated by Django 5.2.1 on 2026-05-21 18:28

import questions.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Exemplos: 2023.0, 2023.1, 2024.2, etc.', max_length=6, validators=[questions.validators.validate_period_format], verbose_name='Nome do Período')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Período',
                'verbose_name_plural': 'historical Períodos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=512)),
                ('title', models.CharField(max_length=150, verbose_name='Enunciado')),
                ('code', models.TextField(help_text="É realizada uma normalização automática para remover espaços em branco extras e padronizar quebras de linha. Ex: '   int main() {\\r\\n' se torna 'int main() {\\n'", max_length=10000, verbose_name='Código')),
                ('description', models.TextField(max_length=10000, verbose_name='Descrição')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('haskell', 'Haskell'), ('prolog', 'Prolog')], max_length=10, verbose_name='Linguagem')),
                ('type', models.CharField(choices=[('basic', 'Básica'), ('advanced', 'Avançada')], default='basic', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizada em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Questão',
                'verbose_name_plural': 'historical Questões',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuestion_tags',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HistoricalQuestion_tags',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome da Tag')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tag',
                'verbose_name_plural': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Entrada')),
                ('output_data', models.TextField(verbose_name='Saída')),
                ('type', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='private', max_length=7, verbose_name='Tipo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Teste',
                'verbose_name_plural': 'historical Testes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplos: 2023.0, 2023.1, 2024.2, etc.', max_length=6, unique=True, validators=[questions.validators.validate_period_format], verbose_name='Nome do Período')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=512)),
                ('title', models.CharField(max_length=150, verbose_name='Enunciado')),
                ('code', models.TextField(help_text="É realizada uma normalização automática para remover espaços em branco extras e padronizar quebras de linha. Ex: '   int main() {\\r\\n' se torna 'int main() {\\n'", max_length=10000, verbose_name='Código')),
                ('description', models.TextField(max_length=10000, verbose_name='Descrição')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('haskell', 'Haskell'), ('prolog', 'Prolog')], max_length=10, verbose_name='Linguagem')),
                ('type', models.CharField(choices=[('basic', 'Básica'), ('advanced', 'Avançada')], default='basic', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Entrada')),
                ('output_data', models.TextField(verbose_name='Saída')),
                ('type', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='private', max_length=7, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
    ]
