# Generated by Django 5.2.1 on 2025-05-29 21:09

import questions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Formato: AAAA.S (ex: 2024.1)', max_length=6, unique=True, validators=[questions.validators.validate_period_format], verbose_name='Nome do Período')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
    ]
