# Generated by Django 5.2.1 on 2025-05-31 22:32

import questions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='Exemplos: 2023.0, 2023.1, 2024.2, etc.', max_length=6, unique=True, validators=[questions.validators.validate_period_format], verbose_name='Nome do Período'),
        ),
    ]
