# Generated by Django 5.2.1 on 2025-05-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_period_name'),
        ('user', '0003_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Enunciado')),
                ('code', models.TextField(verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('language', models.CharField(choices=[('c_cpp', 'C/C++'), ('haskell', 'Haskell'), ('prolog', 'Prolog')], default='c_cpp', max_length=10, verbose_name='Linguagem')),
                ('type', models.CharField(choices=[('basic', 'Básica'), ('advanced', 'Avançada')], default='basic', max_length=10, verbose_name='Tipo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.assistentstudent')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='questions.period')),
                ('tags', models.ManyToManyField(related_name='questions', to='questions.tag')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Entrada')),
                ('output_data', models.TextField(verbose_name='Saída')),
                ('type', models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], default='Privado', max_length=7)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='questions.question')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
    ]
