# Generated by Django 5.2.1 on 2025-06-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tag_question_test'),
        ('user', '0004_alter_customuser_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.assistentstudent', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], default='Privado', max_length=7, verbose_name='Tipo'),
        ),
    ]
