# Generated by Django 5.2.1 on 2025-06-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_slug_alter_question_author_alter_test_type'),
        ('user', '0004_alter_customuser_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='user.assistentstudent', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='question',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='questions.period', verbose_name='Período'),
        ),
    ]
