# Generated by Django 5.2.1 on 2025-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('cplusplus', 'C/C++'), ('haskell', 'Haskell'), ('prolog', 'Prolog')], default='cplusplus', max_length=10, verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Atualizada em'),
        ),
    ]
