# Generated by Django 5.2.1 on 2025-06-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_created_at_alter_question_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='private', max_length=7, verbose_name='Tipo'),
        ),
    ]
