# nginx/nginx.conf

upstream web_app {
    server web:8000;
}

# Redireciona HTTP (80) para HTTPS (443)
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

# Configuração HTTPS
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    client_max_body_size 20M;

    location / {
        proxy_pass http://web_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/app/web/staticfiles/;
    }

    location /media/ {
        alias /home/app/web/mediafiles/;
    }
}