# Generated by Django 5.2.1 on 2025-05-29 21:19

import django.db.models.deletion
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration', models.CharField(max_length=9, unique=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('github', models.URLField(blank=True, max_length=255, verbose_name='GitHub')),
                ('role', models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor')], max_length=10, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='questions.period')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AssistentStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
    ]
