# Generated by Django 5.2.1 on 2026-05-21 18:28

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import user.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Emails só serão enviados para usuários com permissão de login. <br>Desmarque para desativar o usuário, mas não excluí-lo.<br>Usuários inativos não podem fazer login.', verbose_name='Permissão de Login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration', models.CharField(blank=True, help_text='Exemplo: 123456789', max_length=9, null=True, unique=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('github', models.URLField(blank=True, help_text='URL do perfil do GitHub (opcional)', max_length=255, null=True, verbose_name='GitHub')),
                ('role', models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor')], max_length=10, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='questions.period', verbose_name='Período')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AssistentStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='HistoricalAssistentStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Emails só serão enviados para usuários com permissão de login. <br>Desmarque para desativar o usuário, mas não excluí-lo.<br>Usuários inativos não podem fazer login.', verbose_name='Permissão de Login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('registration', models.CharField(blank=True, db_index=True, help_text='Exemplo: 123456789', max_length=9, null=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('github', models.URLField(blank=True, help_text='URL do perfil do GitHub (opcional)', max_length=255, null=True, verbose_name='GitHub')),
                ('role', models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor')], max_length=10, verbose_name='Função')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'historical Monitor',
                'verbose_name_plural': 'historical Monitores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Emails só serão enviados para usuários com permissão de login. <br>Desmarque para desativar o usuário, mas não excluí-lo.<br>Usuários inativos não podem fazer login.', verbose_name='Permissão de Login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('registration', models.CharField(blank=True, db_index=True, help_text='Exemplo: 123456789', max_length=9, null=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('github', models.URLField(blank=True, help_text='URL do perfil do GitHub (opcional)', max_length=255, null=True, verbose_name='GitHub')),
                ('role', models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor')], max_length=10, verbose_name='Função')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'historical User',
                'verbose_name_plural': 'historical Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfessor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Emails só serão enviados para usuários com permissão de login. <br>Desmarque para desativar o usuário, mas não excluí-lo.<br>Usuários inativos não podem fazer login.', verbose_name='Permissão de Login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('registration', models.CharField(blank=True, db_index=True, help_text='Exemplo: 123456789', max_length=9, null=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('github', models.URLField(blank=True, help_text='URL do perfil do GitHub (opcional)', max_length=255, null=True, verbose_name='GitHub')),
                ('role', models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor')], max_length=10, verbose_name='Função')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'historical Professor',
                'verbose_name_plural': 'historical Professores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSystemSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('min_basic_cpp_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em C/C++')),
                ('min_advanced_cpp_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em C/C++')),
                ('min_basic_haskell_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em Haskell')),
                ('min_advanced_haskell_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em Haskell')),
                ('min_basic_prolog_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em Prolog')),
                ('min_advanced_prolog_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em Prolog')),
                ('cpp_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em C/C++.', verbose_name='Prazo para criação de questões em C/C++')),
                ('haskell_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Haskell.', verbose_name='Prazo para criação de questões em Haskell')),
                ('prolog_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Prolog.', verbose_name='Prazo para criação de questões em Prolog')),
                ('min_public_tests_in_questions', models.PositiveIntegerField(default=1, verbose_name='Mínimo de testes públicos em questões')),
                ('min_private_tests_in_questions', models.PositiveIntegerField(default=5, verbose_name='Mínimo de testes privados em questões')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('active_period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.period', verbose_name='Período Ativo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Configurações do Sistema',
                'verbose_name_plural': 'historical Configurações do Sistemas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_basic_cpp_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em C/C++')),
                ('min_advanced_cpp_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em C/C++')),
                ('min_basic_haskell_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em Haskell')),
                ('min_advanced_haskell_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em Haskell')),
                ('min_basic_prolog_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões básicas em Prolog')),
                ('min_advanced_prolog_questions', models.PositiveIntegerField(default=0, verbose_name='Mínimo de questões avançadas em Prolog')),
                ('cpp_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em C/C++.', verbose_name='Prazo para criação de questões em C/C++')),
                ('haskell_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Haskell.', verbose_name='Prazo para criação de questões em Haskell')),
                ('prolog_deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Prolog.', verbose_name='Prazo para criação de questões em Prolog')),
                ('min_public_tests_in_questions', models.PositiveIntegerField(default=1, verbose_name='Mínimo de testes públicos em questões')),
                ('min_private_tests_in_questions', models.PositiveIntegerField(default=5, verbose_name='Mínimo de testes privados em questões')),
                ('active_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.period', verbose_name='Período Ativo')),
            ],
            options={
                'verbose_name': 'Configurações do Sistema',
            },
        ),
    ]
