# Generated by Django 5.2.1 on 2025-05-30 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='questions.period', verbose_name='Período'),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_period', models.ForeignKey(blank=True, help_text='Se definido, apenas monitores com este período poderão acessar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.period', verbose_name='Período Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
