# Generated by Django 5.2.1 on 2025-05-31 22:32

import django.db.models.deletion
import django.utils.timezone
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_period_name'),
        ('user', '0002_alter_customuser_period_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'Configurações do sistema'},
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='cpp_deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em C/C++.', verbose_name='Prazo para criação de questões em C/C++'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='haskell_deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Haskell.', verbose_name='Prazo para criação de questões em Haskell'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_advanced_cpp_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões avançadas que podem ser criadas em C/C++.', verbose_name='Máximo de questões avançadas em C/C++'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_advanced_haskell_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões avançadas que podem ser criadas em Haskell.', verbose_name='Máximo de questões avançadas em Haskell'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_advanced_prolog_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões avançadas que podem ser criadas em Prolog.', verbose_name='Máximo de questões avançadas em Prolog'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_basic_cpp_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões básicas que podem ser criadas em C/C++.', verbose_name='Máximo de questões básicas em C/C++'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_basic_haskell_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões básicas que podem ser criadas em Haskell.', verbose_name='Máximo de questões básicas em Haskell'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_basic_prolog_questions',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de questões básicas que podem ser criadas em Prolog.', verbose_name='Máximo de questões básicas em Prolog'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='prolog_deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora limite para a criação de questões em Prolog.', verbose_name='Prazo para criação de questões em Prolog'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Emails só serão enviados para usuários com permissão de login. <br>Desmarque para desativar o usuário, mas não excluí-lo.<br>Usuários inativos não podem fazer login.', verbose_name='Permissão de Login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration',
            field=models.CharField(help_text='Exemplo: 123456789', max_length=9, unique=True, validators=[user.validators.validate_registration_format], verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='active_period',
            field=models.ForeignKey(blank=True, help_text='• Se definido, apenas monitores com este período terão acesso.<br>• Se deixado em branco, nenhum monitor poderá acessar.<br><b>Atenção:</b> o acesso dos professores deve ser removido manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.period', verbose_name='Período ativo'),
        ),
    ]
