# Generated by Django 5.2.1 on 2025-05-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tag_question_test'),
        ('user', '0003_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='questions.period', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='active_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.period', verbose_name='Período ativo'),
        ),
    ]
