# Generated by Django 5.2.1 on 2025-06-01 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação das configurações do sistema.', verbose_name='Última modificação'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Último modificador'),
        ),
    ]
