# Generated by Django 5.2.1 on 2025-06-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_systemsetting_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'Configurações do Sistema'},
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da última modificação das configurações do sistema.', verbose_name='Última modificação'),
        ),
    ]
