# Generated by Django 5.2.1 on 2025-06-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='min_private_tests_in_questions',
            field=models.PositiveIntegerField(default=5, help_text='Número mínimo de testes privados que devem ser criados em cada questão.', verbose_name='Mínimo de testes privados em questões'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='min_public_tests_in_questions',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de testes públicos que devem ser criados em cada questão.', verbose_name='Mínimo de testes públicos em questões'),
        ),
    ]
