# Generated by Django 5.2.1 on 2026-05-21 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('haskell', 'Haskell'), ('prolog', 'Prolog')], max_length=50, verbose_name='Linguagem')),
                ('source_code', models.TextField(verbose_name='Código')),
                ('activity_type', models.CharField(choices=[('MANUAL', 'Execução Manual'), ('VALIDATION', 'Validação de Questão')], default='MANUAL', max_length=15, verbose_name='Tipo de Atividade')),
                ('manual_inputs', models.TextField(blank=True, null=True, verbose_name='Entradas')),
                ('manual_stdout', models.TextField(blank=True, null=True, verbose_name='Saída Padrão')),
                ('manual_stderr', models.TextField(blank=True, null=True, verbose_name='Saída de Erro')),
                ('manual_verdict', models.CharField(choices=[('PENDING', 'Aguardando Avaliação'), ('AC', 'Aceito'), ('WA', 'Resposta Incorreta'), ('TLE', 'Tempo Limite Excedido'), ('RE', 'Erro de Execução'), ('MLE', 'Memória Excedida'), ('INSECURE', 'Código Potencialmente Inseguro')], default='PENDING', max_length=20)),
                ('verdict', models.CharField(choices=[('PENDING', 'Aguardando Avaliação'), ('AC', 'Aceito'), ('WA', 'Resposta Incorreta'), ('TLE', 'Tempo Limite Excedido'), ('RE', 'Erro de Execução'), ('MLE', 'Memória Excedida'), ('INSECURE', 'Código Potencialmente Inseguro')], default='PENDING', max_length=20, verbose_name='Veredito de Validação')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('COMPLETED', 'Concluído'), ('SYSTEM_ERROR', 'Erro Interno do Sistema')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Tarefa Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
            ],
            options={
                'verbose_name': 'Atividade de Código',
                'verbose_name_plural': 'Atividades de Código',
            },
        ),
        migrations.CreateModel(
            name='ValidationTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False, verbose_name='Teste Aprovado')),
                ('stdout', models.TextField(blank=True, null=True, verbose_name='Saída padrão')),
                ('stderr', models.TextField(blank=True, null=True, verbose_name='Saída de erro')),
            ],
            options={
                'verbose_name': 'Resultado de Teste de Validação',
            },
        ),
    ]
