# Generated by Django 5.2.1 on 2026-05-21 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_compiler', '0002_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Execução'),
        ),
        migrations.CreateModel(
            name='ManualRun',
            fields=[
            ],
            options={
                'verbose_name': 'Execução Manual',
                'verbose_name_plural': 'Execuções Manuais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('code_compiler.codeactivity',),
        ),
        migrations.CreateModel(
            name='QuestionValidation',
            fields=[
            ],
            options={
                'verbose_name': 'Validação de Questão',
                'verbose_name_plural': 'Validações de Questões',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('code_compiler.codeactivity',),
        ),
        migrations.AddField(
            model_name='validationtestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.test', verbose_name='Teste'),
        ),
        migrations.AddField(
            model_name='validationtestresult',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='code_compiler.questionvalidation', verbose_name='Atividade de Validação'),
        ),
    ]
